// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoundTheCode.LinqExpressions_Example.Data;

namespace RoundTheCode.LinqExpressions_Example.Data.Migrations
{
    [DbContext(typeof(LinqExpressionsDbContext))]
    partial class LinqExpressionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RoundTheCode.LinqExpressions_Example.Data.Models.Types.FilmEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("FilmEntities");
                });

            modelBuilder.Entity("RoundTheCode.LinqExpressions_Example.Data.Models.Types.FilmTimeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FilmId");

                    b.Property<DateTimeOffset>("StartTime");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.ToTable("FilmTimeEntities");
                });

            modelBuilder.Entity("RoundTheCode.LinqExpressions_Example.Data.Models.Types.FilmTimeEntity", b =>
                {
                    b.HasOne("RoundTheCode.LinqExpressions_Example.Data.Models.Types.FilmEntity", "Film")
                        .WithMany("FilmTimes")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
